# Exploration du schema des tables DP1 via TAP

- **Auteur** : Sylvie Dagoret-Campagne
- **Date** : 2026-02-28

## JOINs corrects (valides par tests)

| JOIN | Cle | Remarque |
|------|-----|----------|
| `Source` x `Visit` | `src.Visit = v.visit` | OK |
| `Source` x `CcdVisit` | `src.Visit = cv.VisitId` | OK - **sans** `AND detector` |
| `ForcedSource` x `CcdVisit` | `fs.Visit = cv.VisitId` | OK (exemple officiel) |
| `Object` x `ForcedSource` x `CcdVisit` | `obj.objectId = fs.objectId` puis `fs.Visit = cv.VisitId` | OK (exemple officiel) |

## Piege confirme
- `dp1.Source` **n'a PAS de colonne `detector`** -> le JOIN avec CcdVisit est 1-to-many (une source par visite, plusieurs CCDs par visite)
- La casse compte : `Source.Visit` (V majuscule), `CcdVisit.VisitId` (camelCase), `Visit.visit` (minuscule)

## Reference officielle
```sql
-- Source JOIN CcdVisit (doc dp1.lsst.io/tutorials/portal/103/portal-103-4.html)
SELECT src.sourceId, src.band, src.Visit, cv.VisitId, cv.expMidptMJD, cv.seeing
FROM dp1.Source AS src
JOIN dp1.CcdVisit AS cv ON src.Visit = cv.VisitId
WHERE CONTAINS(POINT('ICRS', src.coord_ra, src.coord_dec),
               CIRCLE('ICRS', 53.13, -28.10, 0.05)) = 1
AND src.band = 'i'
```

## 1. Connexion TAP

In [1]:
import os
import pandas as pd
import pyvo
import requests
from IPython.display import display

token = os.environ["RSP_TOKEN"]
session = requests.Session()
session.headers["Authorization"] = f"Bearer {token}"

RSP_TAP_URL = "https://data.lsst.cloud/api/tap"
service = pyvo.dal.TAPService(RSP_TAP_URL, session=session)
print("Connecte :", RSP_TAP_URL)

Connecte : https://data.lsst.cloud/api/tap

In [2]:
def show_schema(service, table_name):
    """Affiche le schema complet d'une table via tap_schema."""
    query = f"""
    SELECT column_name, datatype, description, unit
    FROM tap_schema.columns
    WHERE table_name = '{table_name}'
    ORDER BY column_name
    """
    df = service.search(query).to_table().to_pandas()
    print(f"\n{'='*70}")
    print(f"TABLE : {table_name}  ({len(df)} colonnes)")
    print(f"{'='*70}")
    if len(df) == 0:
        print("  !! Table non trouvee !!")
    else:
        pd.set_option('display.max_rows', None)
        pd.set_option('display.max_colwidth', 80)
        display(df)
    return df

print("OK")

OK

## 2. Liste de toutes les tables DP1

In [3]:
tables_result = service.search("""
    SELECT table_name, description
    FROM tap_schema.tables
    WHERE table_name LIKE 'dp1.%'
    ORDER BY table_name
""").to_table().to_pandas()
display(tables_result)

,table_name,description
0,dp1.CcdVisit,Metadata about the nine individual CCD images ...
1,dp1.CoaddPatches,Static information about the subset of tracts ...
2,dp1.DiaObject,Properties of time-varying astronomical object...
3,dp1.DiaSource,Properties of transient-object detections on t...
4,dp1.ForcedSource,Forced-photometry measurements on individual s...
5,dp1.ForcedSourceOnDiaObject,Point-source forced-photometry measurements on...
6,dp1.MPCORB,Orbit catalog produced by the Minor Planet Cen...
7,dp1.Object,Descriptions of static astronomical objects (o...
8,dp1.Source,Properties of detections on the single-epoch v...
9,dp1.SSObject,LSST-computed per-object quantities. 1:1 relat...
10,dp1.SSSource,LSST-computed per-source quantities. 1:1 relat...
11,dp1.Visit,"Metadata about the pointings of the telescope,..."

## 3. Schemas des tables principales

In [4]:
df_source = show_schema(service, 'dp1.Source')

======================================================================
TABLE : dp1.Source  (156 colonnes)
======================================================================

,column_name,datatype,description,unit
0,ap03Flux,double,Flux within 3.0-pixel aperture,nJy
1,ap03FluxErr,double,Flux uncertainty within 3.0-pixel aperture,nJy
2,ap03Flux_flag,boolean,General Failure Flag,
3,ap06Flux,double,Flux within 6.0-pixel aperture,nJy
4,ap06FluxErr,double,Flux uncertainty within 6.0-pixel aperture,nJy
5,ap06Flux_flag,boolean,General Failure Flag,
6,ap09Flux,double,Flux within 9.0-pixel aperture,nJy
7,ap09FluxErr,double,Flux uncertainty within 9.0-pixel aperture,nJy
8,ap09Flux_flag,boolean,General Failure Flag,
9,ap12Flux,double,Flux within 12.0-pixel aperture,nJy
10,ap12FluxErr,double,Flux uncertainty within 12.0-pixel aperture,nJy
11,ap12Flux_flag,boolean,General Failure Flag,
12,ap17Flux,double,Flux within 17.0-pixel aperture,nJy
13,ap17FluxErr,double,Flux uncertainty within 17.0-pixel aperture,nJy
14,ap17Flux_flag,boolean,General Failure Flag,
15,ap25Flux,double,Flux within 25.0-pixel aperture,nJy
16,ap25FluxErr,double,Flux uncertainty within 25.0-pixel aperture,nJy
17,ap25Flux_flag,boolean,General Failure Flag,
18,ap35Flux,double,Flux within 35.0-pixel aperture,nJy
19,ap35FluxErr,double,Flux uncertainty within 35.0-pixel aperture,nJy
20,ap35Flux_flag,boolean,General Failure Flag,
21,ap50Flux,double,Flux within 50.0-pixel aperture,nJy
22,ap50FluxErr,double,Flux uncertainty within 50.0-pixel aperture,nJy
23,ap50Flux_flag,boolean,General Failure Flag,
24,ap70Flux,double,Flux within 70.0-pixel aperture,nJy
25,ap70FluxErr,double,Flux uncertainty within 70.0-pixel aperture,nJy
26,ap70Flux_flag,boolean,General Failure Flag,
27,apFlux_12_0_flag,boolean,General Failure Flag,
28,apFlux_12_0_flag_apertureTruncated,boolean,Aperture did not fit within measurement image,
29,apFlux_12_0_flag_sincCoeffsTruncated,boolean,Full sinc coefficient image did not fit within measurement image,
30,apFlux_12_0_instFlux,double,Flux within 12.0-pixel aperture,count
31,apFlux_12_0_instFluxErr,double,1-sigma flux uncertainty,count
32,apFlux_17_0_flag,boolean,General Failure Flag,
33,apFlux_17_0_instFlux,double,Flux within 17.0-pixel aperture,count
34,apFlux_17_0_instFluxErr,double,1-sigma flux uncertainty,count
35,apFlux_35_0_flag,boolean,General Failure Flag,
36,apFlux_35_0_instFlux,double,Flux within 35.0-pixel aperture,count
37,apFlux_35_0_instFluxErr,double,1-sigma flux uncertainty,count
38,apFlux_50_0_flag,boolean,General Failure Flag,
39,apFlux_50_0_instFlux,double,Flux within 50.0-pixel aperture,count
40,apFlux_50_0_instFluxErr,double,1-sigma flux uncertainty,count
41,band,char,Name of the band used to take the exposure where this source was measured. A...,
42,blendedness_abs,double,"Measure of how much the flux is affected by neighbors, (1 - child_flux/paren...",
43,blendedness_flag,boolean,General Failure Flag,
44,blendedness_flag_noCentroid,boolean,Object has no centroid,
45,blendedness_flag_noShape,boolean,Object has no shape,
46,calib_astrometry_used,boolean,Set if source was used in astrometric calibration,
47,calibFlux,double,Flux within 12.0-pixel aperture,nJy
48,calibFluxErr,double,Flux uncertainty within 12.0-pixel aperture,nJy
49,calib_photometry_reserved,boolean,Set if source was reserved from photometric calibration,
50,calib_photometry_used,boolean,Set if source was used in photometric calibration,
51,calib_psf_candidate,boolean,"Flag set if the source was a candidate for PSF determination, as determined ...",
52,calib_psf_reserved,boolean,Set if source was reserved from PSF determination,
53,calib_psf_used,boolean,"Flag set if the source was actually used for PSF determination, as determine...",
54,centroid_flag,boolean,General Failure Flag,
55,centroid_flag_almostNoSecondDerivative,boolean,Almost vanishing second derivative,
56,centroid_flag_badError,boolean,Error on x and/or y position is NaN,
57,centroid_flag_edge,boolean,Object too close to edge,
58,centroid_flag_noSecondDerivative,boolean,Vanishing second derivative,
59,centroid_flag_notAtMaximum,boolean,Object is not at a maximum,
60,centroid_flag_resetToPeak,boolean,Set if CentroidChecker reset the centroid,
61,coord_dec,double,Fiducial ICRS Declination of centroid used for database indexing,deg
62,coord_ra,double,Fiducial ICRS Right Ascension of centroid used for database indexing,deg
63,deblend_deblendedAsPsf,boolean,Deblender thought this source looked like a PSF,
64,deblend_hasStrayFlux,boolean,This source was assigned some stray flux,
65,deblend_masked,boolean,Parent footprint was predominantly masked,
66,deblend_nChild,int,Number of children this object has (defaults to 0),
67,deblend_parentTooBig,boolean,Parent footprint covered too many pixels,
68,deblend_patchedTemplate,boolean,This source was near an image edge and the deblender used patched edge-handl...,
69,deblend_rampedTemplate,boolean,This source was near an image edge and the deblender used ramp edge-handling.,
70,deblend_skipped,boolean,Deblender skipped this source,
71,deblend_tooManyPeaks,boolean,Source had too many peaks; only the brightest were included,
72,dec,double,Position in declination.,deg
73,decErr,float,Error in declination.,deg
74,detector,int,Id of the detector where this source was measured.,
75,extendedness,double,Flux-ratio measure of whether an object is point-like (0) or extended (1).,
76,extendedness_flag,boolean,Set to 1 for any fatal failure.,
77,footprintArea_value,int,Number of pixels in the sources detection footprint.,pixel
78,gaussianFlux,double,Flux from Gaussian Flux algorithm,nJy
79,gaussianFluxErr,double,Flux uncertainty from Gaussian Flux algorithm,nJy
80,gaussianFlux_flag,boolean,General Failure Flag,
81,hsmPsfMoments_flag,boolean,"General failure flag, set if anything went wrong",
82,hsmPsfMoments_flag_no_pixels,boolean,No pixels to measure,
83,hsmPsfMoments_flag_not_contained,boolean,Center not contained in footprint bounding box,
84,hsmPsfMoments_flag_parent_source,boolean,"Parent source, ignored",
85,hsmShapeRegauss_flag,boolean,"General failure flag, set if anything went wrong",
86,hsmShapeRegauss_flag_galsim,boolean,GalSim failure,
87,hsmShapeRegauss_flag_no_pixels,boolean,No pixels to measure,
88,hsmShapeRegauss_flag_not_contained,boolean,Center not contained in footprint bounding box,
89,hsmShapeRegauss_flag_parent_source,boolean,"Parent source, ignored",
90,iDebiasedPSF_flag,boolean,"General failure flag, set if anything went wrong",
91,iDebiasedPSF_flag_edge,boolean,Variance undefined outside image edge,
92,iDebiasedPSF_flag_galsim,boolean,GalSim failure,
93,iDebiasedPSF_flag_no_pixels,boolean,No pixels to measure,
94,iDebiasedPSF_flag_not_contained,boolean,Center not contained in footprint bounding box,
95,iDebiasedPSF_flag_parent_source,boolean,"Parent source, ignored",
96,invalidPsfFlag,boolean,Source has an invalid psf.,
97,ixx,double,HSM moments,pixel**2
98,ixxDebiasedPSF,double,HSM moments,pixel**2
99,ixxPSF,double,HSM moments,pixel**2
100,ixy,double,HSM moments,pixel**2
101,ixyDebiasedPSF,double,HSM moments,pixel**2
102,ixyPSF,double,HSM moments,pixel**2
103,iyy,double,HSM moments,pixel**2
104,iyyDebiasedPSF,double,HSM moments,pixel**2
105,iyyPSF,double,HSM moments,pixel**2
106,jacobian_flag,boolean,Set to 1 for any fatal failure,
107,jacobian_value,double,Jacobian correction,
108,localBackground_flag,boolean,General Failure Flag,
109,localBackground_flag_noGoodPixels,boolean,No good pixels in the annulus,
110,localBackground_flag_noPsf,boolean,No PSF provided,
111,localBackground_instFlux,double,Background in annulus around source,count
112,localBackground_instFluxErr,double,1-sigma flux uncertainty,count
113,normCompTophatFlux_flag,boolean,General failure flag for normCompTophatFlux.,
114,normCompTophatFlux_instFlux,double,Normalized compensated tophat flux for calibration,count
115,normCompTophatFlux_instFluxErr,double,1-sigma flux uncertainty on normCompTophatFlux_instFlux,count
116,parentSourceId,long,Unique ID of parent source,
117,physical_filter,char,"ID of physical filter, the filter associated with a particular instrument.",
118,pixelFlags_bad,boolean,Bad pixel in the Source footprint,
119,pixelFlags_cr,boolean,Cosmic ray in the Source footprint,
120,pixelFlags_crCenter,boolean,Cosmic ray in the Source center,
121,pixelFlags_edge,boolean,Source is on the edge of an exposure region (masked EDGE),
122,pixelFlags_interpolated,boolean,Interpolated pixel in the Source footprint,
123,pixelFlags_interpolatedCenter,boolean,Interpolated pixel in the Source center,
124,pixelFlags_nodata,boolean,Source is outside usable exposure region (masked NO_DATA),
125,pixelFlags_offimage,boolean,Source center is off image,
126,pixelFlags_saturated,boolean,Saturated pixel in the Source footprint,
127,pixelFlags_saturatedCenter,boolean,Saturated pixel in the Source center,
128,pixelFlags_suspect,boolean,Sources footprint includes suspect pixels,
129,pixelFlags_suspectCenter,boolean,Sources center is close to suspect pixels,
130,psfFlux,double,Flux derived from linear least-squares fit of psf model forced on the calexp,nJy
131,psfFlux_apCorr,double,Aperture correction applied to base_PsfFlux,
132,psfFlux_apCorrErr,double,Standard deviation of aperture correction applied to base_PsfFlux,
133,psfFlux_area,float,Effective area of PSF,pixel
134,psfFluxErr,double,Uncertainty on the flux derived from linear least-squares fit of psf model f...,nJy
135,psfFlux_flag,boolean,Failure to derive linear least-squares fit of psf model forced on the calexp,
136,psfFlux_flag_apCorr,boolean,Set if unable to aperture correct base_PsfFlux,
137,psfFlux_flag_edge,boolean,Object was too close to the edge of the image to use the full PSF model,
138,psfFlux_flag_noGoodPixels,boolean,Not enough non-rejected pixels in data to attempt the fit,
139,ra,double,Position in right ascension.,deg
140,ra_dec_Cov,float,Covariance between right ascension and declination.,deg**2
141,raErr,float,Error in right ascension.,deg
142,sizeExtendedness,double,Moments-based measure of a source to be a galaxy.,
143,sizeExtendedness_flag,boolean,Set to 1 for any fatal failure.,
144,sky,double,Background in annulus around source,nJy
145,skyErr,double,Background in annulus around source,nJy
146,sky_source,boolean,Sky objects.,
147,sourceId,long,Unique id. Unique Source ID. Primary Key.,
148,variance_flag,boolean,Set for any fatal failure,
149,variance_flag_emptyFootprint,boolean,Set to True when the footprint has no usable pixels,
150,variance_value,double,Variance at object position,
151,visit,long,Id of the visit where this source was measured.,
152,x,double,Centroid from Sdss Centroid algorithm,pixel
153,xErr,float,1-sigma uncertainty on x position,pixel
154,y,double,Centroid from Sdss Centroid algorithm,pixel
155,yErr,float,1-sigma uncertainty on y position,pixel

In [5]:
df_visit = show_schema(service, 'dp1.Visit')

======================================================================
TABLE : dp1.Visit  (15 colonnes)
======================================================================

,column_name,datatype,description,unit
0,airmass,double,Airmass of the observed line of sight.,
1,altitude,double,Altitude of focal plane center at the middle of the visit.,deg
2,azimuth,double,Azimuth of focal plane center at the middle of the visit.,deg
3,band,char,Name of the band used to take the visit where this source was measured. Abst...,
4,dec,double,Declination of focal plane center,deg
5,expMidpt,char,Midpoint time for exposure at the fiducial center of the focal plane array. ...,
6,expMidptMJD,double,Midpoint time for exposure at the fiducial center of the focal plane array i...,d
7,expTime,double,"Spatially-averaged duration of visit, accurate to 10ms.",s
8,obsStart,char,"Start time of the visit at the fiducial center of the focal plane array, TAI...",
9,obsStartMJD,double,"Start of the exposure in MJD, TAI, accurate to 10ms.",d
10,physical_filter,char,"ID of physical filter, the filter associated with a particular instrument.",
11,ra,double,Right Ascension of focal plane center.,deg
12,skyRotation,double,Sky rotation angle.,deg
13,visit,long,Unique identifier.,
14,zenithDistance,double,Zenith distance at the middle of the visit.,deg

In [6]:
df_ccdvisit = show_schema(service, 'dp1.CcdVisit')

======================================================================
TABLE : dp1.CcdVisit  (50 colonnes)
======================================================================

,column_name,datatype,description,unit
0,astromOffsetMean,double,Mean offset of astrometric calibration matches (arcsec),arcsec
1,astromOffsetStd,double,Standard deviation of offsets of astrometric calibration matches (arcsec),arcsec
2,band,char,Name of the band used to take the visit where this source was measured. Abst...,
3,ccdVisitId,long,Primary key (unique identifier).,
4,darkTime,double,"Average dark current accumulation time, accurate to 10ms.",s
5,dec,double,Declination of Ccd center.,deg
6,detector,long,Detector ID. A detector associated with a particular instrument (not an obse...,
7,effTime,double,Effective time metric,s
8,effTimePsfSigmaScale,double,Effective time metric -- PSF size component,
9,effTimeSkyBgScale,double,Effective time metric -- Sky background component,
10,effTimeZeroPointScale,double,Effective time metric -- Throughput component,
11,expMidpt,char,Midpoint time for exposure at the fiducial center of the focal plane array. ...,
12,expMidptMJD,double,Midpoint time for exposure at the fiducial center of the focal plane array i...,d
13,expTime,double,"Spatially-averaged duration of visit, accurate to 10ms.",s
14,llcdec,double,Declination of lower left corner.,deg
15,llcra,double,Right Ascension of lower left corner.,deg
16,lrcdec,double,Declination of lower right corner.,deg
17,lrcra,double,Right Ascension of lower right corner.,deg
18,magLim,double,5-sigma limiting magnitude,mag
19,maxDistToNearestPsf,double,Maximum distance of an unmasked pixel to its nearest model psf star (pixel),pixel
20,nPsfStar,int,Number of stars used for PSF model,
21,obsStart,char,"Start of the visit, TAI, accurate to 10ms.",
22,obsStartMJD,double,"Start of the exposure in MJD, TAI, accurate to 10ms.",d
23,physical_filter,char,"ID of physical filter, the filter associated with a particular instrument.",
24,pixelScale,float,Measured detector pixel scale.,arcsec/pixel
25,psfApCorrSigmaScaledDelta,double,Delta (max - min) of psf flux aperture correction factors scaled (divided) b...,
26,psfApFluxDelta,double,"Delta (max - min) of model psf aperture flux (with aperture radius of max(2,...",
27,psfSigma,float,PSF model second-moments determinant radius (center of chip),pixel
28,psfStarDeltaE1Median,double,Median E1 residual (starE1 - psfE1) for psf stars,
29,psfStarDeltaE1Scatter,double,Scatter (via MAD) of E1 residual (starE1 - psfE1) for psf stars,
30,psfStarDeltaE2Median,double,Median E2 residual (starE2 - psfE2) for psf stars,
31,psfStarDeltaE2Scatter,double,Scatter (via MAD) of E2 residual (starE2 - psfE2) for psf stars,
32,psfStarDeltaSizeMedian,double,Median size residual (starSize - psfSize) for psf stars (pixel),pixel
33,psfStarDeltaSizeScatter,double,Scatter (via MAD) of size residual (starSize - psfSize) for stars (pixel),pixel
34,psfStarScaledDeltaSizeScatter,double,Scatter (via MAD) of size residual scaled by median size squared,
35,psfTraceRadiusDelta,double,Delta (max - min) of model psf trace radius values evaluated on a grid of un...,pixel
36,ra,double,Right Ascension of Ccd center.,deg
37,seeing,double,Mean measured FWHM of the PSF.,arcsec
38,skyBg,float,Average sky background.,adu
39,skyNoise,float,RMS noise of the sky background.,adu
40,skyRotation,double,Sky rotation angle.,deg
41,ulcdec,double,Declination of upper left corner.,deg
42,ulcra,double,Right Ascension of upper left corner.,deg
43,urcdec,double,Declination of upper right corner.,deg
44,urcra,double,Right Ascension of upper right corner.,deg
45,visitId,long,Reference to the corresponding entry in the Visit table.,
46,xSize,long,Number of columns in the image.,pixel
47,ySize,long,Number of rows in the image.,pixel
48,zenithDistance,float,Zenith distance at observation mid-point.,deg
49,zeroPoint,float,"Zero-point for the Ccd, estimated at Ccd center.",mag

In [7]:
df_forcedsource = show_schema(service, 'dp1.ForcedSource')

======================================================================
TABLE : dp1.ForcedSource  (28 colonnes)
======================================================================

,column_name,datatype,description,unit
0,band,char,Abstract filter that is not associated with a particular instrument,
1,coord_dec,double,Fiducial ICRS Declination of centroid used for database indexing,deg
2,coord_ra,double,Fiducial ICRS Right Ascension of centroid used for database indexing,deg
3,detector,long,Id of the detector where this source was measured.,
4,diff_PixelFlags_nodataCenter,boolean,Source center is outside usable region on image difference (masked NO_DATA),
5,invalidPsfFlag,boolean,Source has an invalid PSF.,
6,objectId,long,Unique Object ID. Primary Key of the Object Table,
7,parentObjectId,long,Unique ObjectId of the parent of the ObjectId in context of the deblender.,
8,patch,long,Skymap patch ID,
9,pixelFlags_bad,boolean,Bad pixel in the Source footprint,
10,pixelFlags_cr,boolean,Cosmic ray in the Source footprint,
11,pixelFlags_crCenter,boolean,Cosmic ray in the Source center,
12,pixelFlags_edge,boolean,Source is on the edge of an exposure region (masked EDGE),
13,pixelFlags_interpolated,boolean,Interpolated pixel in the Source footprint,
14,pixelFlags_interpolatedCenter,boolean,Interpolated pixel in the Source center,
15,pixelFlags_nodata,boolean,Source is outside usable exposure region (masked NO_DATA),
16,pixelFlags_saturated,boolean,Saturated pixel in the Source footprint,
17,pixelFlags_saturatedCenter,boolean,Saturated pixel in the Source center,
18,pixelFlags_suspect,boolean,Sources footprint includes suspect pixels,
19,pixelFlags_suspectCenter,boolean,Sources center is close to suspect pixels,
20,psfDiffFlux,float,Flux derived from linear least-squares fit of psf model forced on the image ...,nJy
21,psfDiffFluxErr,float,Uncertainty on the flux derived from linear least-squares fit of psf model f...,nJy
22,psfDiffFlux_flag,boolean,Failure to derive linear least-squares fit of psf model forced on the image ...,
23,psfFlux,float,Flux derived from linear least-squares fit of psf model forced on the calexp,nJy
24,psfFluxErr,float,Uncertainty on the flux derived from linear least-squares fit of psf model f...,nJy
25,psfFlux_flag,boolean,Failure to derive linear least-squares fit of psf model forced on the calexp,
26,tract,long,Skymap tract ID,
27,visit,long,Id of the visit where this source was measured.,

In [8]:
df_diasource = show_schema(service, 'dp1.DiaSource')

======================================================================
TABLE : dp1.DiaSource  (87 colonnes)
======================================================================

,column_name,datatype,description,unit
0,apFlux,float,Flux in a 12 pixel radius aperture on the difference image.,nJy
1,apFluxErr,float,Estimated uncertainty of apFlux.,nJy
2,apFlux_flag,boolean,General aperture flux algorithm failure flag; set if anything went wrong whe...,
3,apFlux_flag_apertureTruncated,boolean,Aperture did not fit within measurement image.,
4,band,char,Band used to take this observation.,
5,bboxSize,long,Bounding box of diaSource footprint.,
6,centroid_flag,boolean,General centroid algorithm failure flag; set if anything went wrong when fit...,
7,coord_dec,double,Fiducial ICRS Declination of centroid used for database indexing.,deg
8,coord_ra,double,Fiducial ICRS Right Ascension of centroid used for database indexing.,deg
9,dec,double,Position in declination.,deg
10,decErr,float,Error in declination.,deg
11,detector,long,Id of the detector where this diaSource was measured.,
12,diaObjectId,long,Id of the DiaObject that this DiaSource was associated with.,
13,diaSourceId,long,Unique identifier of this DiaSource.,
14,dipoleAngle,double,Dipole orientation,deg
15,dipoleChi2,double,Chi2 per degree of freedom of dipole fit.,
16,dipoleFitAttempted,boolean,Attempted to fit a dipole model to this source.,
17,dipoleFluxDiff,double,"Raw flux counts, positive lobe.",nJy
18,dipoleFluxDiffErr,double,"Raw flux uncertainty counts, positive lobe.",nJy
19,dipoleLength,double,Pixel separation between positive and negative lobes of dipole.,pixel
20,dipoleMeanFlux,double,"Raw flux counts, positive lobe.",count
21,dipoleMeanFluxErr,double,"Raw flux uncertainty counts, positive lobe.",count
22,dipoleNdata,long,Number of data points in the dipole fit,
23,extendedness,double,"A measure of extendedness, computed by comparing an object's moment-based tr...",
24,forced_PsfFlux_flag,boolean,Forced PSF photometry on science image failed. Another forced_PsfFlux flag f...,
25,forced_PsfFlux_flag_edge,boolean,Forced PSF flux object was too close to the edge of the image to use the ful...,
26,forced_PsfFlux_flag_noGoodPixels,boolean,Forced PSF flux not enough non-rejected pixels in data to attempt the fit.,
27,isDipole,boolean,Source well fit by a dipole.,
28,ixx,double,Elliptical Gaussian adaptive moments.,arcsec**2
29,ixxPSF,double,Adaptive moments of the PSF model at the object position.,arcsec**2
30,ixy,double,Elliptical Gaussian adaptive moments.,arcsec**2
31,ixyPSF,double,Adaptive moments of the PSF model at the object position.,arcsec**2
32,iyy,double,Elliptical Gaussian adaptive moments.,arcsec**2
33,iyyPSF,double,Adaptive moments of the PSF model at the object position.,arcsec**2
34,midpointMjdTai,double,"Mid-exposure time for the Visit for this DiaSource, expressed as Modified Ju...",d
35,parentDiaSourceId,long,Unique ID of parent source.,
36,pixelFlags,boolean,General pixel flags failure; set if anything went wrong when setting pixels ...,
37,pixelFlags_bad,boolean,Bad pixel in the DiaSource footprint.,
38,pixelFlags_cr,boolean,Cosmic ray in the DiaSource footprint.,
39,pixelFlags_crCenter,boolean,Cosmic ray in the 3x3 region around the centroid.,
40,pixelFlags_edge,boolean,Some of the source footprint is outside usable exposure region (masked EDGE ...,
41,pixelFlags_injected,boolean,Injection in the DiaSource footprint.,
42,pixelFlags_injectedCenter,boolean,Injection in the 3x3 region around the centroid.,
43,pixelFlags_injected_template,boolean,Template injection in the DiaSource footprint.,
44,pixelFlags_injected_templateCenter,boolean,Template injection in the 3x3 region around the centroid.,
45,pixelFlags_interpolated,boolean,Interpolated pixel in the DiaSource footprint.,
46,pixelFlags_interpolatedCenter,boolean,Interpolated pixel in the 3x3 region around the centroid.,
47,pixelFlags_nodata,boolean,NO_DATA pixel in the source footprint.,
48,pixelFlags_nodataCenter,boolean,NO_DATA pixel in the 3x3 region around the centroid.,
49,pixelFlags_offimage,boolean,DiaSource center is off image.,
50,pixelFlags_saturated,boolean,Saturated pixel in the DiaSource footprint.,
51,pixelFlags_saturatedCenter,boolean,Saturated pixel in the 3x3 region around the centroid.,
52,pixelFlags_streak,boolean,Streak in the DiaSource footprint.,
53,pixelFlags_streakCenter,boolean,Streak in the 3x3 region around the centroid.,
54,pixelFlags_suspect,boolean,DiaSource's footprint includes suspect pixels.,
55,pixelFlags_suspectCenter,boolean,Suspect pixel in the 3x3 region around the centroid.,
56,psfChi2,float,Chi^2 statistic of the point source model fit.,
57,psfFlux,float,Flux derived from linear least-squares fit of PSF model.,nJy
58,psfFluxErr,float,Flux uncertainty derived from linear least-squares fit of PSF model.,nJy
59,psfFlux_flag,boolean,Failure to derive linear least-squares fit of psf model. Another psfFlux fla...,
60,psfFlux_flag_edge,boolean,Object was too close to the edge of the image to use the full PSF model.,
61,psfFlux_flag_noGoodPixels,boolean,Not enough non-rejected pixels in data to attempt the fit.,
62,psfNdata,int,Number of pixels that were included in the PSF fit.,pixel
63,ra,double,Position in right ascension.,deg
64,ra_dec_Cov,float,Covariance between right ascension and declination.,deg**2
65,raErr,float,Error in right ascension.,deg
66,reliability,float,"A measure of reliability, computed using information from the source and ima...",
67,scienceFlux,float,Forced PSF flux measured on the direct image.,nJy
68,scienceFluxErr,float,Forced PSF flux uncertainty measured on the direct image.,nJy
69,shape_flag,boolean,General source shape algorithm failure flag; set if anything went wrong when...,
70,shape_flag_no_pixels,boolean,No pixels to measure shape.,
71,shape_flag_not_contained,boolean,Center not contained in footprint bounding box.,
72,shape_flag_parent_source,boolean,This source is a parent source; we should only be measuring on deblended chi...,
73,snr,double,Ratio of apFlux/apFluxErr,
74,ssObjectId,long,"Id of the ssObject this source was associated with, if any. If not, it is se...",
75,time_processed,char,Time when the image was processed and this DiaSource record was generated.,
76,trailAngle,double,Angle measured from +x-axis.,
77,trailDec,double,Trail centroid declination.,deg
78,trail_flag_edge,boolean,This flag is set if a trailed source contains edge pixels.,
79,trailFlux,float,Trailed source flux.,nJy
80,trailLength,double,Trail length.,pixel
81,trailRa,double,Trail centroid right ascension.,deg
82,visit,long,Id of the visit where this diaSource was measured.,
83,x,double,"Unweighted first moment centroid, overall centroid",pixel
84,xErr,float,1-sigma uncertainty on x position,pixel
85,y,double,"Unweighted first moment centroid, overall centroid",pixel
86,yErr,float,1-sigma uncertainty on y position,pixel

In [9]:
df_object = show_schema(service, 'dp1.Object')

======================================================================
TABLE : dp1.Object  (1296 colonnes)
======================================================================

,column_name,datatype,description,unit
0,coord_dec,double,Fiducial ICRS Declination of centroid used for database indexing,deg
1,coord_decErr,float,Error in fiducial ICRS Declination of centroid,deg
2,coord_ra,double,Fiducial ICRS Right Ascension of centroid used for database indexing,deg
3,coord_ra_dec_Cov,float,Covariance between fiducial ICRS Right Ascension and Declination of centroid,deg**2
4,coord_raErr,float,Error in fiducial ICRS Right Ascension of centroid,deg
5,deblend_failed,boolean,Deblender failed to deblend this source,
6,deblend_incompleteData,boolean,One or more bands were not deblended due to an inability to model the PSF.,
7,deblend_isolatedParent,boolean,Deblender skipped this footprint because there was only a single peak,
8,deblend_iterations,int,Number of iterations during deblending,
9,deblend_logL,float,Log likelihood of the entire blend in scarlet_lite.,
10,deblend_masked,boolean,Deblender skipped this source because there were too many masked pixels.,
11,deblend_nChild,int,Number of children this object has (defaults to 0),
12,deblend_nPeaks,int,Number of peaks this parent footprint has (even if the deblender failed or s...,
13,deblend_parentTooBig,boolean,Deblender skipped this source because the parent footprint was too large.,
14,deblend_peak_center_x,int,x-coordinate of the peak after source detection,pixel
15,deblend_peak_center_y,int,y-coordinate of the peak after source detection,pixel
16,deblend_skipped,boolean,Deblender skipped this source,
17,deblend_tooManyPeaks,boolean,Deblender skipped this source because there were too many peaks in the Footp...,
18,detect_fromBlend,boolean,This source is deblended from a parent with more than one child.,
19,detect_isDeblendedModelSource,boolean,True if source has no children and is in the inner region of a coadd patch a...,
20,detect_isIsolated,boolean,This source is not a part of a blend.,
21,ebv,float,"E(B-V) at coord_ra/coord_dec per Schlegel, Finkbeiner & Davis (1998)",mag
22,footprintArea,int,Number of pixels in the sources detection footprint. Reference band.,pixel
23,g_ap03Flux,float,Flux within 3.0-pixel aperture. Forced on g-band.,nJy
24,g_ap03FluxErr,float,Flux uncertainty within 3.0-pixel aperture. Forced on g-band.,nJy
25,g_ap03Flux_flag,boolean,Flag set for any failure with the 3.0-pixel aperture flux. Forced on g-band.,
26,g_ap06Flux,float,Flux within 6.0-pixel aperture. Forced on g-band.,nJy
27,g_ap06FluxErr,float,Flux uncertainty within 6.0-pixel aperture. Forced on g-band.,nJy
28,g_ap06Flux_flag,boolean,Flag set for any failure with the 6.0-pixel aperture flux. Forced on g-band.,
29,g_ap09Flux,float,Flux within 9.0-pixel aperture. Forced on g-band.,nJy
30,g_ap09FluxErr,float,Flux uncertainty within 9.0-pixel aperture. Forced on g-band.,nJy
31,g_ap09Flux_flag,boolean,Flag set for any failure with the 9.0-pixel aperture flux. Forced on g-band.,
32,g_ap12Flux,float,Flux within 12.0-pixel aperture. Forced on g-band.,nJy
33,g_ap12FluxErr,float,Flux uncertainty within 12.0-pixel aperture. Forced on g-band.,nJy
34,g_ap12Flux_flag,boolean,Flag set for any failure with the 12.0-pixel aperture flux. Forced on g-band.,
35,g_ap17Flux,float,Flux within 17.0-pixel aperture. Forced on g-band.,nJy
36,g_ap17FluxErr,float,Flux uncertainty within 17.0-pixel aperture. Forced on g-band.,nJy
37,g_ap17Flux_flag,boolean,Flag set for any failure with the 17.0-pixel aperture flux. Forced on g-band.,
38,g_ap25Flux,float,Flux within 25.0-pixel aperture. Forced on g-band.,nJy
39,g_ap25FluxErr,float,Flux uncertainty within 25.0-pixel aperture. Forced on g-band.,nJy
40,g_ap25Flux_flag,boolean,Flag set for any failure with the 25.0-pixel aperture flux. Forced on g-band.,
41,g_ap35Flux,float,Flux within 35.0-pixel aperture. Forced on g-band.,nJy
42,g_ap35FluxErr,float,Flux uncertainty within 35.0-pixel aperture. Forced on g-band.,nJy
43,g_ap35Flux_flag,boolean,Flag set for any failure with the 35.0-pixel aperture flux. Forced on g-band.,
44,g_ap50Flux,float,Flux within 50.0-pixel aperture. Forced on g-band.,nJy
45,g_ap50FluxErr,float,Flux uncertainty within 50.0-pixel aperture. Forced on g-band.,nJy
46,g_ap50Flux_flag,boolean,Flag set for any failure with the 50.0-pixel aperture flux. Forced on g-band.,
47,g_ap70Flux,float,Flux within 70.0-pixel aperture. Forced on g-band.,nJy
48,g_ap70FluxErr,float,Flux uncertainty within 70.0-pixel aperture. Forced on g-band.,nJy
49,g_ap70Flux_flag,boolean,Flag set for any failure with the 70.0-pixel aperture flux. Forced on g-band.,
50,g_apFlux_flag,boolean,Duplicate of g_ap12Flux_flag.,
51,g_apFlux_flag_apertureTruncated,boolean,Duplicate of g_ap12Flux_flag_apertureTruncated.,
52,g_apFlux_flag_sincCoeffsTruncated,boolean,Duplicate of g_ap12Flux_flag_sincCoeffsTruncated. Measured on g-band.,
53,g_bdChi2,float,-ln(likelihood) (chi^2) in CModel fit. Measured on g-band.,
54,g_bdE1,float,Flux-weighted average of exponential and de Vaucouleurs ellipticities. Measu...,pixel**2
55,g_bdE2,float,Flux-weighted average of exponential and de Vaucouleurs ellipticities. Measu...,pixel**2
56,g_bdFluxB,float,Flux from the de Vaucouleurs fit. Measured on g-band.,nJy
57,g_bdFluxBErr,float,Flux uncertainty from the de Vaucouleurs fit. Measured on g-band.,nJy
58,g_bdFluxD,float,Flux from the exponential fit. Measured on g-band.,nJy
59,g_bdFluxDErr,float,Flux uncertainty from the exponential fit. Measured on g-band.,nJy
60,g_bdReB,float,Half-light ellipse of the de Vaucouleurs fit. Measured on g-band.,pixel**2
61,g_bdReD,float,Half-light ellipse of the exponential fit. Measured on g-band.,pixel**2
62,g_blendedness,float,"Measure of how much the flux is affected by neighbors, (1 - child_flux/paren...",
63,g_blendedness_flag,boolean,Flag set for any failure in the blendedness algorithm. Measured on g-band.,
64,g_calib_astrometry_used,boolean,Propagated from sources. Measured on g-band.,
65,g_calibFlux,float,Duplicate of g_ap12Flux.,nJy
66,g_calibFluxErr,float,Duplicate of g_ap12FluxErr.,nJy
67,g_calibFlux_flag,boolean,Duplicate of g_ap12Flux_flag.,
68,g_calibFlux_flag_apertureTruncated,boolean,Duplicate of g_ap12Flux_flag_apertureTruncated.,
69,g_calibFlux_flag_sincCoeffsTruncated,boolean,Duplicate of g_ap12Flux_flag_sincCoeffsTruncated. Measured on g-band.,
70,g_calib_photometry_reserved,boolean,Propagated from sources. Measured on g-band.,
71,g_calib_photometry_used,boolean,Propagated from sources. Measured on g-band.,
72,g_calib_psf_candidate,boolean,Propagated from sources. Measured on g-band.,
73,g_calib_psf_reserved,boolean,Propagated from sources. Measured on g-band.,
74,g_calib_psf_used,boolean,Propagated from sources. Measured on g-band.,
75,g_centroid_flag,boolean,Flag set for any failure in the centroid algorithm. Measured on g-band.,
76,g_centroid_x,double,Centroid from the SDSS centroid algorithm. Measured on g-band.,pixel
77,g_centroid_xErr,float,1-sigma uncertainty on x position. Measured on g-band.,pixel
78,g_centroid_y,double,Centroid from the SDSS centroid algorithm. Measured on g-band.,pixel
79,g_centroid_yErr,float,1-sigma uncertainty on y position. Measured on g-band.,pixel
80,g_cModel_flag,boolean,Flag set if the final CModel fit (or any previous fit) failed. Forced on g-b...,
81,g_cModel_flag_apCorr,boolean,Flag set if unable to aperture-correct the CModel flux. Forced on g-band.,
82,g_cModelFlux,float,Flux from the final CModel fit. Forced on g-band.,nJy
83,g_cModelFluxErr,float,Flux uncertainty from the final CModel fit. Forced on g-band.,nJy
84,g_cModelFlux_inner,float,"Flux within the fit region, with no extrapolation. Forced on g-band.",nJy
85,g_cModelMag,float,AB magnitude of cModelFlux. Forced on g-band.,mag
86,g_cModelMagErr,float,Uncertainty in magnitudes on cModelFlux. Forced on g-band.,mag
87,g_deblend_blendedness,float,Blendedness in the deconvolved scarlet space.,
88,g_deblend_dataCoverage,float,"Fraction of data that contained good data, ie. 1 - number of no data pixels/...",
89,g_deblend_fluxOverlap,float,The total flux from neighboring objects that overlaps with this sources foot...,
90,g_deblend_fluxOverlapFraction,float,Fraction of flux from neighbors / source flux in the deconvolved footprint.,
91,g_deblend_zeroFlux,boolean,True when there was no flux attributed to this object after flux redistribut...,
92,g_dec,double,"Position in declination, measured on g-band.",deg
93,g_decErr,float,"Error in declination, measured on g-band.",deg
94,g_epoch,double,Mean epoch of the object in the g-band coadd in MJD TAI,d
95,g_extendedness,float,Flux-ratio measure of whether an object is point-like (0) or extended (1). M...,
96,g_extendedness_flag,boolean,Flag set for any failure in the flux-ratio extendedness. Measured on g-band.,
97,g_free_cModelFlux,float,Flux from the final CModel fit. Measured on g-band.,nJy
98,g_free_cModelFluxErr,float,Flux uncertainty from the final CModel fit. Measured on g-band.,nJy
99,g_free_cModelFlux_flag,boolean,Flag set if the final CModel fit (or any previous fit) failed. Measured on g...,
100,g_free_cModelFlux_inner,float,"Flux within the fit region, with no extrapolation. Measured on g-band.",nJy
101,g_free_psfFlux,float,Flux derived from using the PSF model as a weight function. Measured on g-band.,nJy
102,g_free_psfFluxErr,float,Flux uncertainty derived from using the PSF model as a weight function. Meas...,nJy
103,g_free_psfFlux_flag,boolean,Flag set if the unforced PSF flux failed in this band for any reason. Measur...,
104,g_gaap0p7Flux,float,GAaP Flux with 0.7 arcsec aperture after reconvolving the image to a Gaussia...,nJy
105,g_gaap0p7FluxErr,float,GAaP Flux uncertainty with 0.7 arcsec aperture after multiplying the seeing ...,nJy
106,g_gaap0p7Flux_flag_bigPsf,boolean,The Gaussianized PSF is bigger than the aperture. Forced on g-band.,
107,g_gaap1p0Flux,float,GAaP Flux with 1.0 arcsec aperture after reconvolving the image to a Gaussia...,nJy
108,g_gaap1p0FluxErr,float,GAaP Flux uncertainty with 1.0 arcsec aperture after multiplying the seeing ...,nJy
109,g_gaap1p0Flux_flag_bigPsf,boolean,The Gaussianized PSF is bigger than the aperture. Forced on g-band.,
110,g_gaap1p5Flux,float,GAaP Flux with 1.5 arcsec aperture after reconvolving the image to a Gaussia...,nJy
111,g_gaap1p5FluxErr,float,GAaP Flux uncertainty with 1.5 arcsec aperture after multiplying the seeing ...,nJy
112,g_gaap1p5Flux_flag_bigPsf,boolean,The Gaussianized PSF is bigger than the aperture. Forced on g-band.,
113,g_gaap2p5Flux,float,GAaP Flux with 2.5 arcsec aperture after reconvolving the image to a Gaussia...,nJy
114,g_gaap2p5FluxErr,float,GAaP Flux uncertainty with 2.5 arcsec aperture after multiplying the seeing ...,nJy
115,g_gaap2p5Flux_flag_bigPsf,boolean,The Gaussianized PSF is bigger than the aperture. Forced on g-band.,
116,g_gaap3p0Flux,float,GAaP Flux with 3.0 arcsec aperture after reconvolving the image to a Gaussia...,nJy
117,g_gaap3p0FluxErr,float,GAaP Flux uncertainty with 3.0 arcsec aperture after multiplying the seeing ...,nJy
118,g_gaap3p0Flux_flag_bigPsf,boolean,The Gaussianized PSF is bigger than the aperture. Forced on g-band.,
119,g_gaapFlux_flag,boolean,Flag set for any failure in the GAaP photometry. Forced on g-band.,
120,g_gaapFlux_flag_edge,boolean,Source is too close to the edge. Forced on g-band.,
121,g_gaapFlux_flag_gaussianization,boolean,PSF Gaussianization failed when trying to scale by this factor. Forced on g-...,
122,g_gaapOptimalFlux,float,GAaP Flux with optimal aperture after reconvolving the image to a Gaussian P...,nJy
123,g_gaapOptimalFluxErr,float,GAaP Flux uncertainty with optimal aperture after multiplying the seeing by ...,nJy
124,g_gaapOptimalFlux_flag_bigPsf,boolean,The Gaussianized PSF is bigger than the aperture. Forced on g-band.,
125,g_gaapPsfFlux,float,GAaP Flux with PSF aperture after reconvolving the image to a Gaussian PSF l...,nJy
126,g_gaapPsfFluxErr,float,GAaP Flux uncertainty with PSF aperture after multiplying the seeing by 1.15...,nJy
127,g_hsm_moments_03,float,HSM higher-order moment 03. Measured on g-band.,
128,g_hsm_moments_04,float,HSM higher-order moment 04. Measured on g-band.,
129,g_hsm_moments_12,float,HSM higher-order moment 12. Measured on g-band.,
130,g_hsm_moments_13,float,HSM higher-order moment 13. Measured on g-band.,
131,g_hsm_moments_21,float,HSM higher-order moment 21. Measured on g-band.,
132,g_hsm_moments_22,float,HSM higher-order moment 22. Measured on g-band.,
133,g_hsm_moments_30,float,HSM higher-order moment 30. Measured on g-band.,
134,g_hsm_moments_31,float,HSM higher-order moment 31. Measured on g-band.,
135,g_hsm_moments_40,float,HSM higher-order moment 40. Measured on g-band.,
136,g_hsm_moments_flag,boolean,Flag set for any failure in the HSM higher-order moments. Measured on g-band.,
137,g_hsm_momentsPsf_03,float,HSM higher-order moment 03 measured on the PSF model at the position of the ...,
138,g_hsm_momentsPsf_04,float,HSM higher-order moment 04 measured on the PSF model at the position of the ...,
139,g_hsm_momentsPsf_12,float,HSM higher-order moment 12 measured on the PSF model at the position of the ...,
140,g_hsm_momentsPsf_13,float,HSM higher-order moment 13 measured on the PSF model at the position of the ...,
141,g_hsm_momentsPsf_21,float,HSM higher-order moment 21 measured on the PSF model at the position of the ...,
142,g_hsm_momentsPsf_22,float,HSM higher-order moment 22 measured on the PSF model at the position of the ...,
143,g_hsm_momentsPsf_30,float,HSM higher-order moment 30 measured on the PSF model at the position of the ...,
144,g_hsm_momentsPsf_31,float,HSM higher-order moment 31 measured on the PSF model at the position of the ...,
145,g_hsm_momentsPsf_40,float,HSM higher-order moment 40 measured on the PSF model at the position of the ...,
146,g_hsm_momentsPsf_flag,boolean,Flag set for any failure in the HSM higher-order moment on the PSF model. Me...,
147,g_hsmShapeRegauss_e1,float,PSF-corrected shear using the Hirata & Seljak (2003) Regaussianization algor...,
148,g_hsmShapeRegauss_e2,float,PSF-corrected shear using the Hirata & Seljak (2003) Regaussianization algor...,
149,g_hsmShapeRegauss_flag,boolean,Flag set for any failure with the Regaussianziation shapes. Measured on g-band.,
150,g_hsmShapeRegauss_sigma,float,PSF-corrected shear using the Hirata & Seljak (2003) Regaussianization algor...,
151,g_iDebiasedPSF_flag,boolean,Flag set for any failure in the debiased PSF model moments. Measured on g-band.,
152,g_i_flag,boolean,"General failure flag, set if anything went wrong. Measured on g-band.",
153,g_inputCount,int,"Number of images contributing at center, not including any clipping. Forced ...",
154,g_inputCount_flag,boolean,Flag set for any failure in computing the number of inputs. Forced on g-band.,
155,g_inputCount_flag_noInputs,boolean,No coadd inputs were recorded. Forced on g-band.,
156,g_invalidPsfFlag,boolean,This object has an invalid PSF (usually no inputs). Measured on g-band.,
157,g_iPSF_flag,boolean,Flag set for any failure in the PSF model moments. Measured on g-band.,
158,g_iRound_flag,boolean,Flag set for any failure in the round moments. Measured on g-band.,
159,g_ixx,float,Gaussian-weighted adaptive moments. Measured on g-band.,pixel**2
160,g_ixxDebiasedPSF,float,Gaussian-weighted adaptive moments of the PSF model at the position of the o...,pixel**2
161,g_ixxPSF,float,Gaussian-weighted adaptive moments of the PSF model at the position of this ...,pixel**2
162,g_ixxRound,float,Adaptive moments using an isotropic Gaussian weight function. Measured on g-...,pixel**2
163,g_ixy,float,Gaussian-weighted adaptive moments. Measured on g-band.,pixel**2
164,g_ixyDebiasedPSF,float,Gaussian-weighted adaptive moments of the PSF model at the position of the o...,pixel**2
165,g_ixyPSF,float,Gaussian-weighted adaptive moments. Measured on g-band.,pixel**2
166,g_ixyRound,float,Adaptive moments using an isotropic Gaussian weight function. Measured on g-...,pixel**2
167,g_iyy,float,Gaussian-weighted adaptive moments. Measured on g-band.,pixel**2
168,g_iyyDebiasedPSF,float,Gaussian-weighted adaptive moments of the PSF model at the position of the o...,pixel**2
169,g_iyyPSF,float,Gaussian-weighted adaptive moments of the PSF model at the position of this ...,pixel**2
170,g_iyyRound,float,Adaptive moments using an isotropic Gaussian weight function. Measured on g-...,pixel**2
171,g_kronFlux,float,Flux measured within an elliptical aperture 2.5 times the Kron radius. Meas...,nJy
172,g_kronFluxErr,float,Flux uncertainty from Kron Flux algorithm. Measured on g-band.,nJy
173,g_kronFlux_flag,boolean,Flag set for any failure in the Kron photometry. Measured on g-band.,
174,g_kronFlux_flag_bad_radius,boolean,Bad Kron radius. Measured on g-band.,
175,g_kronFlux_flag_bad_shape,boolean,Shape for measuring Kron radius is bad; used PSF shape. Measured on g-band.,
176,g_kronFlux_flag_bad_shape_no_psf,boolean,Bad shape and no PSF. Measured on g-band.,
177,g_kronFlux_flag_edge,boolean,Bad measurement due to image edge. Measured on g-band.,
178,g_kronFlux_flag_no_fallback_radius,boolean,No minimum radius and no PSF provided. Measured on g-band.,
179,g_kronFlux_flag_no_minimum_radius,boolean,"Minimum radius could not enforced, no minimum value or PSF. Measured on g-band.",
180,g_kronFlux_flag_small_radius,boolean,Measured Kron radius was smaller than that of the PSF. Measured on g-band.,
181,g_kronFlux_flag_used_minimum_radius,boolean,Used the minimum radius for the Kron radius. Measured on g-band.,
182,g_kronFlux_flag_used_psf_radius,boolean,Kron radius fell back to being derived from the PSF radius. Measured on g-band.,
183,g_kronRad,float,Kron radius (sqrt(a*b)). Measured on g-band.,
184,g_pixelFlags_bad,boolean,Deprecated; only set when there is no g-band data.,
185,g_pixelFlags_clipped,boolean,Artifacts were rejected by warp comparison in this object's footprint. Measu...,
186,g_pixelFlags_clippedCenter,boolean,Artifacts were rejected by warp comparison in this object's center. Measured...,
187,g_pixelFlags_cr,boolean,A cosmic ray was detected and interpolated in this object's footprint. Measu...,
188,g_pixelFlags_crCenter,boolean,A cosmic ray was detected and interpolated in this object's center. Measured...,
189,g_pixelFlags_edge,boolean,Deprecated; only set when there is no g-band data.,
190,g_pixelFlags_inexact_psf,boolean,The PSF model is discontinuous in this object's footprint. Measured on g-band.,
191,g_pixelFlags_inexact_psfCenter,boolean,The PSF model is discontinuosu near this object's center. Measured on g-band.,
192,g_pixelFlags_interpolated,boolean,An interpolated pixel contributed to the coadd in this object's footprint. M...,
193,g_pixelFlags_interpolatedCenter,boolean,An interpolated pixel contributed to the coadd near this object's center. Me...,
194,g_pixelFlags_nodata,boolean,No pixel data was available in this band for this object. Measured on g-band.,
195,g_pixelFlags_offimage,boolean,Deprecated; only set when there is no g-band data.,
196,g_pixelFlags_saturated,boolean,"Saturated pixels were rejected from this object's footprint, but would other...",
197,g_pixelFlags_saturatedCenter,boolean,"Saturated pixels were rjected from near this object's center, but would othe...",
198,g_pixelFlags_sensor_edge,boolean,A detector boundary passed through this object's footprint. Measured on g-band.,
199,g_pixelFlags_sensor_edgeCenter,boolean,A detector boundary passed close to this object's center. Measured on g-band.,
200,g_pixelFlags_suspect,boolean,Deprecated; only set when there is no g-band data.,
201,g_pixelFlags_suspectCenter,boolean,Deprecated; only set when there is no g-band data.,
202,g_psfFlux,float,Flux derived from using the PSF model as a weight function. Forced on g-band.,nJy
203,g_psfFlux_area,float,Effective area of PSF. Forced on g-band.,pixel
204,g_psfFluxErr,float,Flux uncertainty derived from using the PSF model as a weight function. Forc...,nJy
205,g_psfFlux_flag,boolean,General Failure Flag. Forced on g-band.,

In [10]:
df_diaobject = show_schema(service, 'dp1.DiaObject')

======================================================================
TABLE : dp1.DiaObject  (137 colonnes)
======================================================================

,column_name,datatype,description,unit
0,dec,double,Declination coordinate of the position of the diaObject at time radecMjdTai.,deg
1,diaObjectId,long,Unique identifier of this DiaObject.,
2,g_psfFluxChi2,float,Chi^2 statistic for the scatter of g_psfFlux around g_psfFluxMean,
3,g_psfFluxErrMean,float,Mean of the diaSource PSF flux errors,nJy
4,g_psfFluxLinearIntercept,double,y-intercept of a linear model fit to diaSource PSF flux vs time,nJy
5,g_psfFluxLinearSlope,double,Slope of a linear model fit to diaSource PSF flux vs time,nJy/d
6,g_psfFluxMAD,float,Median absolute deviation of diaSource PSF flux. Does not include scale fact...,nJy
7,g_psfFluxMax,double,Maximum diaSource PSF flux,nJy
8,g_psfFluxMaxSlope,double,Maximum ratio of time ordered deltaFlux / deltaTime,nJy/d
9,g_psfFluxMean,double,Weighted mean of diaSource PSF flux,nJy
10,g_psfFluxMeanErr,double,Standard error on the weighted mean of diaSource PSF flux,nJy
11,g_psfFluxMin,double,Minimum diaSource PSF flux,nJy
12,g_psfFluxNdata,double,The number of data points used to compute g_psfFluxChi2,
13,g_psfFluxPercentile05,double,5th percentile diaSource PSF flux,nJy
14,g_psfFluxPercentile25,double,10th percentile diaSource PSF flux,nJy
15,g_psfFluxPercentile50,double,Median diaSource PSF flux,nJy
16,g_psfFluxPercentile75,double,75th percentile diaSource PSF flux,nJy
17,g_psfFluxPercentile95,double,95th percentile diaSource PSF flux,nJy
18,g_psfFluxSigma,double,Standard deviation of the distribution of g_psfFlux,nJy
19,g_psfFluxSkew,float,Skew of diaSource PSF flux,
20,g_psfFluxStetsonJ,double,StetsonJ statistic of diaSource PSF flux,
21,g_scienceFluxMean,double,Weighted mean of the PSF flux forced photometered at the diaSource position ...,nJy
22,g_scienceFluxMeanErr,double,Standard error on g_scienceFluxMean,nJy
23,g_scienceFluxSigma,double,Standard deviation of the PSF flux forced photometered at the diaSource posi...,nJy
24,i_psfFluxChi2,float,Chi^2 statistic for the scatter of i_psfFlux around i_psfFluxMean,
25,i_psfFluxErrMean,float,Mean of the diaSource PSF flux errors,nJy
26,i_psfFluxLinearIntercept,double,y-intercept of a linear model fit to diaSource PSF flux vs time,nJy
27,i_psfFluxLinearSlope,double,Slope of a linear model fit to diaSource PSF flux vs time,nJy/d
28,i_psfFluxMAD,float,Median absolute deviation of diaSource PSF flux. Does not include scale fact...,nJy
29,i_psfFluxMax,double,Maximum diaSource PSF flux,nJy
30,i_psfFluxMaxSlope,double,Maximum ratio of time ordered deltaFlux / deltaTime,nJy/d
31,i_psfFluxMean,double,Weighted mean of diaSource PSF flux,nJy
32,i_psfFluxMeanErr,double,Standard error on the weighted mean of diaSource PSF flux,nJy
33,i_psfFluxMin,double,Minimum diaSource PSF flux,nJy
34,i_psfFluxNdata,double,The number of data points used to compute i_psfFluxChi2,
35,i_psfFluxPercentile05,double,5th percentile diaSource PSF flux,nJy
36,i_psfFluxPercentile25,double,10th percentile diaSource PSF flux,nJy
37,i_psfFluxPercentile50,double,Median diaSource PSF flux,nJy
38,i_psfFluxPercentile75,double,75th percentile diaSource PSF flux,nJy
39,i_psfFluxPercentile95,double,95th percentile diaSource PSF flux,nJy
40,i_psfFluxSigma,double,Standard deviation of the distribution of i_psfFlux,nJy
41,i_psfFluxSkew,float,Skew of diaSource PSF flux,
42,i_psfFluxStetsonJ,double,StetsonJ statistic of diaSource PSF flux,
43,i_scienceFluxMean,double,Weighted mean of the PSF flux forced photometered at the diaSource position ...,nJy
44,i_scienceFluxMeanErr,double,Standard error on i_scienceFluxMean,nJy
45,i_scienceFluxSigma,double,Standard deviation of the PSF flux forced photometered at the diaSource posi...,nJy
46,nDiaSources,long,Number of diaSources associated with this diaObject.,
47,ra,double,Right Ascension coordinate of the position of the diaObject at time radecMjd...,deg
48,radecMjdTai,double,"Time at which the object was at a position ra/dec, expressed as Modified Jul...",d
49,r_psfFluxChi2,float,Chi^2 statistic for the scatter of r_psfFlux around r_psfFluxMean,
50,r_psfFluxErrMean,float,Mean of the diaSource PSF flux errors,nJy
51,r_psfFluxLinearIntercept,double,y-intercept of a linear model fit to diaSource PSF flux vs time,nJy
52,r_psfFluxLinearSlope,double,Slope of a linear model fit to diaSource PSF flux vs time,nJy/d
53,r_psfFluxMAD,float,Median absolute deviation of diaSource PSF flux. Does not include scale fact...,nJy
54,r_psfFluxMax,double,Maximum diaSource PSF flux,nJy
55,r_psfFluxMaxSlope,double,Maximum ratio of time ordered deltaFlux / deltaTime,nJy/d
56,r_psfFluxMean,double,Weighted mean of diaSource PSF flux,nJy
57,r_psfFluxMeanErr,double,Standard error on the weighted mean of diaSource PSF flux,nJy
58,r_psfFluxMin,double,Minimum diaSource PSF flux,nJy
59,r_psfFluxNdata,double,The number of data points used to compute r_psfFluxChi2,
60,r_psfFluxPercentile05,double,5th percentile diaSource PSF flux,nJy
61,r_psfFluxPercentile25,double,10th percentile diaSource PSF flux,nJy
62,r_psfFluxPercentile50,double,Median diaSource PSF flux,nJy
63,r_psfFluxPercentile75,double,75th percentile diaSource PSF flux,nJy
64,r_psfFluxPercentile95,double,95th percentile diaSource PSF flux,nJy
65,r_psfFluxSigma,double,Standard deviation of the distribution of r_psfFlux,nJy
66,r_psfFluxSkew,float,Skew of diaSource PSF flux,
67,r_psfFluxStetsonJ,double,StetsonJ statistic of diaSource PSF flux,
68,r_scienceFluxMean,double,Weighted mean of the PSF flux forced photometered at the diaSource position ...,nJy
69,r_scienceFluxMeanErr,double,Standard error on r_scienceFluxMean,nJy
70,r_scienceFluxSigma,double,Standard deviation of the PSF flux forced photometered at the diaSource posi...,nJy
71,u_psfFluxChi2,float,Chi^2 statistic for the scatter of u_psfFlux around u_psfFluxMean,
72,u_psfFluxErrMean,float,Mean of the diaSource PSF flux errors,nJy
73,u_psfFluxLinearIntercept,double,y-intercept of a linear model fit to diaSource PSF flux vs time,nJy
74,u_psfFluxLinearSlope,double,Slope of a linear model fit to diaSource PSF flux vs time,nJy/d
75,u_psfFluxMAD,float,Median absolute deviation of diaSource PSF flux. Does not include scale fact...,nJy
76,u_psfFluxMax,double,Maximum diaSource PSF flux,nJy
77,u_psfFluxMaxSlope,double,Maximum ratio of time ordered deltaFlux / deltaTime,nJy/d
78,u_psfFluxMean,double,Weighted mean of diaSource PSF flux,nJy
79,u_psfFluxMeanErr,double,Standard error on the weighted mean of diaSource PSF flux,nJy
80,u_psfFluxMin,double,Minimum diaSource PSF flux,nJy
81,u_psfFluxNdata,double,The number of data points used to compute u_psfFluxChi2,
82,u_psfFluxPercentile05,double,5th percentile diaSource PSF flux,nJy
83,u_psfFluxPercentile25,double,10th percentile diaSource PSF flux,nJy
84,u_psfFluxPercentile50,double,Median diaSource PSF flux,nJy
85,u_psfFluxPercentile75,double,75th percentile diaSource PSF flux,nJy
86,u_psfFluxPercentile95,double,95th percentile diaSource PSF flux,nJy
87,u_psfFluxSigma,double,Standard deviation of the distribution of u_psfFlux,nJy
88,u_psfFluxSkew,float,Skew of diaSource PSF flux,
89,u_psfFluxStetsonJ,double,StetsonJ statistic of diaSource PSF flux,
90,u_scienceFluxMean,double,Weighted mean of the PSF flux forced photometered at the diaSource position ...,nJy
91,u_scienceFluxMeanErr,double,Standard error on u_scienceFluxMean,nJy
92,u_scienceFluxSigma,double,Standard deviation of the PSF flux forced photometered at the diaSource posi...,nJy
93,y_psfFluxChi2,float,Chi^2 statistic for the scatter of y_psfFlux around y_psfFluxMean,
94,y_psfFluxErrMean,float,Mean of the diaSource PSF flux errors,nJy
95,y_psfFluxLinearIntercept,double,y-intercept of a linear model fit to diaSource PSF flux vs time,nJy
96,y_psfFluxLinearSlope,double,Slope of a linear model fit to diaSource PSF flux vs time,nJy/d
97,y_psfFluxMAD,float,Median absolute deviation of diaSource PSF flux. Does not include scale fact...,nJy
98,y_psfFluxMax,double,Maximum diaSource PSF flux,nJy
99,y_psfFluxMaxSlope,double,Maximum ratio of time ordered deltaFlux / deltaTime,nJy/d
100,y_psfFluxMean,double,Weighted mean of diaSource PSF flux,nJy
101,y_psfFluxMeanErr,double,Standard error on the weighted mean of diaSource PSF flux,nJy
102,y_psfFluxMin,double,Minimum diaSource PSF flux,nJy
103,y_psfFluxNdata,double,The number of data points used to compute y_psfFluxChi2,
104,y_psfFluxPercentile05,double,5th percentile diaSource PSF flux,nJy
105,y_psfFluxPercentile25,double,10th percentile diaSource PSF flux,nJy
106,y_psfFluxPercentile50,double,Median diaSource PSF flux,nJy
107,y_psfFluxPercentile75,double,75th percentile diaSource PSF flux,nJy
108,y_psfFluxPercentile95,double,95th percentile diaSource PSF flux,nJy
109,y_psfFluxSigma,double,Standard deviation of the distribution of y_psfFlux,nJy
110,y_psfFluxSkew,float,Skew of diaSource PSF flux,
111,y_psfFluxStetsonJ,double,StetsonJ statistic of diaSource PSF flux,
112,y_scienceFluxMean,double,Weighted mean of the PSF flux forced photometered at the diaSource position ...,nJy
113,y_scienceFluxMeanErr,double,Standard error on y_scienceFluxMean,nJy
114,y_scienceFluxSigma,double,Standard deviation of the PSF flux forced photometered at the diaSource posi...,nJy
115,z_psfFluxChi2,float,Chi^2 statistic for the scatter of z_psfFlux around z_psfFluxMean,
116,z_psfFluxErrMean,float,Mean of the diaSource PSF flux errors,nJy
117,z_psfFluxLinearIntercept,double,y-intercept of a linear model fit to diaSource PSF flux vs time,nJy
118,z_psfFluxLinearSlope,double,Slope of a linear model fit to diaSource PSF flux vs time,nJy/d
119,z_psfFluxMAD,float,Median absolute deviation of diaSource PSF flux. Does not include scale fact...,nJy
120,z_psfFluxMax,double,Maximum diaSource PSF flux,nJy
121,z_psfFluxMaxSlope,double,Maximum ratio of time ordered deltaFlux / deltaTime,nJy/d
122,z_psfFluxMean,double,Weighted mean of diaSource PSF flux,nJy
123,z_psfFluxMeanErr,double,Standard error on the weighted mean of diaSource PSF flux,nJy
124,z_psfFluxMin,double,Minimum diaSource PSF flux,nJy
125,z_psfFluxNdata,double,The number of data points used to compute z_psfFluxChi2,
126,z_psfFluxPercentile05,double,5th percentile diaSource PSF flux,nJy
127,z_psfFluxPercentile25,double,10th percentile diaSource PSF flux,nJy
128,z_psfFluxPercentile50,double,Median diaSource PSF flux,nJy
129,z_psfFluxPercentile75,double,75th percentile diaSource PSF flux,nJy
130,z_psfFluxPercentile95,double,95th percentile diaSource PSF flux,nJy
131,z_psfFluxSigma,double,Standard deviation of the distribution of z_psfFlux,nJy
132,z_psfFluxSkew,float,Skew of diaSource PSF flux,
133,z_psfFluxStetsonJ,double,StetsonJ statistic of diaSource PSF flux,
134,z_scienceFluxMean,double,Weighted mean of the PSF flux forced photometered at the diaSource position ...,nJy
135,z_scienceFluxMeanErr,double,Standard error on z_scienceFluxMean,nJy
136,z_scienceFluxSigma,double,Standard deviation of the PSF flux forced photometered at the diaSource posi...,nJy

## 4. Recap des colonnes de JOIN par table

In [11]:
tables = {
    'dp1.Source':       df_source,
    'dp1.Visit':        df_visit,
    'dp1.CcdVisit':     df_ccdvisit,
    'dp1.ForcedSource': df_forcedsource,
    'dp1.DiaSource':    df_diasource,
    'dp1.Object':       df_object,
    'dp1.DiaObject':    df_diaobject,
}

join_candidates = ['visit', 'Visit', 'visitId', 'VisitId', 'detector',
                   'ccdVisitId', 'objectId', 'diaObjectId', 'sourceId', 'diaSourceId']

print(f"{'Table':<25}  Colonnes de JOIN presentes")
print('-'*70)
for tname, tdf in tables.items():
    if tdf is not None and len(tdf) > 0:
        found = [c for c in join_candidates if c in tdf['column_name'].values]
        print(f"{tname:<25}  {found}")

Table                      Colonnes de JOIN presentes
----------------------------------------------------------------------
dp1.Source                 ['visit', 'detector', 'sourceId']
dp1.Visit                  ['visit']
dp1.CcdVisit               ['visitId', 'detector', 'ccdVisitId']
dp1.ForcedSource           ['visit', 'detector', 'objectId']
dp1.DiaSource              ['visit', 'detector', 'diaObjectId', 'diaSourceId']
dp1.Object                 ['objectId']
dp1.DiaObject              ['diaObjectId']

## 5. Tests de JOIN (requetes de validation)

D'apres les tests precedents et la doc officielle dp1.lsst.io :
- `Source` n'a **pas** de colonne `detector` -> JOIN avec CcdVisit sur `Visit = VisitId` uniquement
- Le JOIN est donc 1-to-many : plusieurs CCDs par visite

In [12]:
# Test 1 : Source JOIN CcdVisit
# Cle : src.Visit = cv.VisitId  (sans AND detector)
# Ref : dp1.lsst.io/tutorials/portal/103/portal-103-4.html
print("Test 1 : Source JOIN CcdVisit  (src.Visit = cv.VisitId, sans detector)")
try:
    res1 = service.search("""
        SELECT TOP 5
            src.sourceId, src.Visit, src.band, src.psfFlux,
            cv.VisitId, cv.expMidptMJD, cv.seeing, cv.zeroPoint, cv.magLim
        FROM dp1.Source AS src
        JOIN dp1.CcdVisit AS cv ON src.Visit = cv.VisitId
        WHERE CONTAINS(
            POINT('ICRS', src.coord_ra, src.coord_dec),
            CIRCLE('ICRS', 53.13, -28.10, 0.05)
        ) = 1
        AND src.band = 'g'
    """).to_table().to_pandas()
    print(f"  OK - {len(res1)} lignes")
    display(res1)
except Exception as e:
    print(f"  ERREUR : {e}")

Test 1 : Source JOIN CcdVisit  (src.Visit = cv.VisitId, sans detector)
  OK - 5 lignes

,sourceId,Visit,band,psfFlux,VisitId,expMidptMJD,seeing,zeroPoint,magLim
0,600320190329653091,2024110800266,g,1015.433222,2024110800266,60623.274265,1.183205,32.078899,24.7481
1,600320190329653091,2024110800266,g,1015.433222,2024110800266,60623.274265,1.187859,32.077099,24.7698
2,600320190329653091,2024110800266,g,1015.433222,2024110800266,60623.274265,1.191796,32.076302,24.7442
3,600320190329653091,2024110800266,g,1015.433222,2024110800266,60623.274265,1.216140,32.075901,24.7030
4,600320190329653091,2024110800266,g,1015.433222,2024110800266,60623.274265,1.188101,32.078602,24.7570

In [13]:
# Test 2 : Source JOIN Visit JOIN CcdVisit (triple)
print("Test 2 : Source JOIN Visit JOIN CcdVisit (triple)")
try:
    res2 = service.search("""
        SELECT TOP 5
            src.sourceId, src.Visit, src.band,
            src.psfFlux, src.psfFluxErr,
            v.expMidptMJD, v.airmass,
            cv.VisitId, cv.seeing, cv.zeroPoint, cv.magLim, cv.skyBg, cv.skyNoise
        FROM dp1.Source AS src
        JOIN dp1.Visit    AS v  ON src.Visit = v.visit
        JOIN dp1.CcdVisit AS cv ON src.Visit = cv.VisitId
        WHERE CONTAINS(
            POINT('ICRS', src.coord_ra, src.coord_dec),
            CIRCLE('ICRS', 53.13, -28.10, 0.05)
        ) = 1
        AND src.band = 'g'
    """).to_table().to_pandas()
    print(f"  OK - {len(res2)} lignes")
    display(res2)
except Exception as e:
    print(f"  ERREUR : {e}")

Test 2 : Source JOIN Visit JOIN CcdVisit (triple)
  OK - 5 lignes

,sourceId,Visit,band,psfFlux,psfFluxErr,expMidptMJD,airmass,VisitId,seeing,zeroPoint,magLim,skyBg,skyNoise
0,600320190329653091,2024110800266,g,1015.433222,115.385564,60623.274265,1.065913,2024110800266,1.183205,32.078899,24.7481,435.773987,24.916901
1,600320190329653091,2024110800266,g,1015.433222,115.385564,60623.274265,1.065913,2024110800266,1.187859,32.077099,24.7698,440.821991,21.669800
2,600320190329653091,2024110800266,g,1015.433222,115.385564,60623.274265,1.065913,2024110800266,1.191796,32.076302,24.7442,440.308990,24.076200
3,600320190329653091,2024110800266,g,1015.433222,115.385564,60623.274265,1.065913,2024110800266,1.216140,32.075901,24.7030,434.510986,23.580099
4,600320190329653091,2024110800266,g,1015.433222,115.385564,60623.274265,1.065913,2024110800266,1.188101,32.078602,24.7570,438.098999,22.790199

In [14]:
# Test 3 : Object JOIN ForcedSource JOIN CcdVisit (exemple officiel - deja valide)
print("Test 3 : Object JOIN ForcedSource JOIN CcdVisit (exemple officiel)")
try:
    res3 = service.search("""
        SELECT TOP 5
            obj.objectId, obj.refExtendedness,
            scisql_nanojanskyToAbMag(fs.psfFlux) AS fs_psfAbMag,
            cv.VisitId, cv.expMidptMJD, cv.seeing
        FROM dp1.Object AS obj
        JOIN dp1.ForcedSource AS fs ON obj.objectId = fs.objectId
        JOIN dp1.CcdVisit     AS cv ON fs.Visit     = cv.VisitId
        WHERE CONTAINS(
            POINT('ICRS', obj.coord_ra, obj.coord_dec),
            CIRCLE('ICRS', 53.13, -28.10, 0.05)
        ) = 1
        AND obj.refExtendedness = 1
        AND fs.band = 'g'
    """).to_table().to_pandas()
    print(f"  OK - {len(res3)} lignes")
    display(res3)
except Exception as e:
    print(f"  ERREUR : {e}")

Test 3 : Object JOIN ForcedSource JOIN CcdVisit (exemple officiel)
  OK - 5 lignes

,objectId,refExtendedness,fs_psfAbMag,VisitId,expMidptMJD,seeing
0,611254385447554248,1.0,25.517561,2024120600078,60651.094041,1.244865
1,611254385447554248,1.0,25.517561,2024120600078,60651.094041,1.187256
2,611254385447554248,1.0,25.517561,2024120600078,60651.094041,1.152859
3,611254385447554248,1.0,25.517561,2024120600078,60651.094041,1.182875
4,611254385447554248,1.0,25.517561,2024120600078,60651.094041,1.135589

In [15]:
# Test 4 : DiaSource JOIN Visit JOIN CcdVisit
# On teste les deux casses possibles pour dia.visit
print("Test 4 : DiaSource JOIN Visit JOIN CcdVisit")
for visit_col in ['visit', 'Visit']:
    try:
        res4 = service.search(f"""
            SELECT TOP 3
                dia.diaSourceId, dia.{visit_col}, dia.band, dia.psfFlux,
                v.expMidptMJD, v.airmass,
                cv.seeing, cv.zeroPoint
            FROM dp1.DiaSource AS dia
            JOIN dp1.Visit    AS v  ON dia.{visit_col} = v.visit
            JOIN dp1.CcdVisit AS cv ON dia.{visit_col} = cv.VisitId
            WHERE CONTAINS(
                POINT('ICRS', dia.coord_ra, dia.coord_dec),
                CIRCLE('ICRS', 53.13, -28.10, 0.05)
            ) = 1
            AND dia.band = 'g'
        """).to_table().to_pandas()
        print(f"  OK avec dia.{visit_col} - {len(res4)} lignes")
        display(res4)
        break
    except Exception as e:
        print(f"  ERREUR avec dia.{visit_col} : {e}")

Test 4 : DiaSource JOIN Visit JOIN CcdVisit
  OK avec dia.visit - 3 lignes

,diaSourceId,visit,band,psfFlux,expMidptMJD,airmass,seeing,zeroPoint
0,600320192611876868,2024110800283,g,24915.199219,60623.292555,1.112068,1.169730,32.069000
1,600320192611876868,2024110800283,g,24915.199219,60623.292555,1.112068,1.128123,32.071400
2,600320192611876868,2024110800283,g,24915.199219,60623.292555,1.112068,1.133330,32.069302

## 6. Requete principale pour l'analyse de saturation Gaia

Version finale corrigee : Source JOIN Visit JOIN CcdVisit sans colonne `detector` dans Source.

In [16]:
# Parametres
RA_CENTER  = 53.0
DEC_CENTER = -28.0
RADIUS_DEG = 1.75
LSST_MAG_LIMIT = 20.5
FLUX_LIMIT = 10**(-0.4 * (LSST_MAG_LIMIT - 31.4))

query_final = f"""
SELECT
    src.sourceId,
    src.Visit,
    src.band,
    src.coord_ra  AS ra,
    src.coord_dec AS dec,
    src.psfFlux,
    src.psfFluxErr,
    v.expMidptMJD,
    v.airmass,
    cv.VisitId,
    cv.seeing,
    cv.zeroPoint,
    cv.magLim,
    cv.skyBg,
    cv.skyNoise
FROM dp1.Source AS src
JOIN dp1.Visit    AS v  ON src.Visit = v.visit
JOIN dp1.CcdVisit AS cv ON src.Visit = cv.VisitId
WHERE CONTAINS(
    POINT('ICRS', src.coord_ra, src.coord_dec),
    CIRCLE('ICRS', {RA_CENTER}, {DEC_CENTER}, {RADIUS_DEG})
) = 1
AND src.psfFlux > {FLUX_LIMIT}
AND src.band = 'g'
"""

print("Requete finale (Source JOIN Visit JOIN CcdVisit) :")
print(query_final)

Requete finale (Source JOIN Visit JOIN CcdVisit) :

SELECT
    src.sourceId,
    src.Visit,
    src.band,
    src.coord_ra  AS ra,
    src.coord_dec AS dec,
    src.psfFlux,
    src.psfFluxErr,
    v.expMidptMJD,
    v.airmass,
    cv.VisitId,
    cv.seeing,
    cv.zeroPoint,
    cv.magLim,
    cv.skyBg,
    cv.skyNoise
FROM dp1.Source AS src
JOIN dp1.Visit    AS v  ON src.Visit = v.visit
JOIN dp1.CcdVisit AS cv ON src.Visit = cv.VisitId
WHERE CONTAINS(
    POINT('ICRS', src.coord_ra, src.coord_dec),
    CIRCLE('ICRS', 53.0, -28.0, 1.75)
) = 1
AND src.psfFlux > 22908.6765276777
AND src.band = 'g'

In [17]:
# Execution asynchrone (necessaire pour les grandes requetes)
print("Soumission du job asynchrone...")
job = service.submit_job(query_final)
job.run()
job.wait(phases=["COMPLETED", "ERROR"])
print("Job phase:", job.phase)
if job.phase == "ERROR":
    job.raise_if_error()

df = job.fetch_result().to_table().to_pandas()
print(f"Resultat : {len(df)} lignes, {len(df.columns)} colonnes")
print("Colonnes :", df.columns.tolist())
df.head(3)

Soumission du job asynchrone...
Job phase: COMPLETED
Resultat : 1604205 lignes, 15 colonnes
Colonnes : ['sourceId', 'Visit', 'band', 'ra', 'dec', 'psfFlux', 'psfFluxErr', 'expMidptMJD', 'airmass', 'VisitId', 'seeing', 'zeroPoint', 'magLim', 'skyBg', 'skyNoise']

,sourceId,Visit,band,ra,dec,psfFlux,psfFluxErr,expMidptMJD,airmass,VisitId,seeing,zeroPoint,magLim,skyBg,skyNoise
0,600412549304811753,2024112900266,g,52.723334,-28.612956,71491.831847,288.542128,60644.257691,1.19374,2024112900266,1.108639,32.040401,24.6693,500.583008,26.283800
1,600412549304811753,2024112900266,g,52.723334,-28.612956,71491.831847,288.542128,60644.257691,1.19374,2024112900266,1.128576,32.040798,24.6980,505.597992,23.002001
2,600412549304811753,2024112900266,g,52.723334,-28.612956,71491.831847,288.542128,60644.257691,1.19374,2024112900266,1.155142,32.039700,24.6584,504.859009,25.265699

In [18]:
len(df)

1604205

In [19]:
df.to_csv("merged_sourcevisitvisitCCD.csv")